### ISSUE TITLE
Entering Spotify

### ISSUE THREAD

**Issue by jonatanolofsson** [akezeke/spotyxbmc#1]
When trying to enter spotify in xbmc, i get a "Remote share" dialog saying "Path no found or invalid".

Looking in the xbmc log file, i find 

18:51:15 T:3061450640 M:1513390080   ERROR: CGUIMediaWindow::GetDirectory(spotify://menu/) failed

It seems, from the log and the cache, that the connection and login is working however.

Ill be happy to provide more debug info

Keep up the good work!

Best regards,
Jonatan Olofsson

**Comment by jonatanolofsson** [comment]
It seems that CMusicSpotifyDirectory::GetDirectory isn't called (the call should have generated a log call: CLog::Log(LOGERROR, "  Spotifylog: get directory %s ", strPath.c_str());

I'm not sure where it should be called from, but that's the magic of open source, to be allowed to dig myself =)
Any pointers appreciated =)

**Comment by jonatanolofsson** [comment]
Issue resolved:
It seems that in xbmc/FileSystem/FactoryDirectory.cpp, two lines disappeared between alpha009 and alpha010

The lines
#include "SpotifyDirectory.h"

and 
if (strProtocol == "spotify") return new CMusicSpotifyDirectory();

should be added in their respective place (as in alpha009)

Best regards,
Jonatan Olofsson

**Comment by akezeke** [comment]
Hi,

Ok thanks for noticing, I will fix that asap!

**Comment by akezeke** [comment]
Jonatan, you should get the latest source and diff from here: git@github.com:akezeke/spotyxbmc.git
