### ISSUE TITLE
SpotyXBMC and DSPlayer?

### ISSUE THREAD

**Issue by nicodemuz-zz** [akezeke/spotyxbmc#14]
I would like a SpotyXBMC version built upon the DSPlayer version of XBMC.

See http://forum.xbmc.org/showthread.php?t=61355 for more info.

I understand that different branches of XBMC cannot be built together in all sort of combinations so the best would be to get both the SpotyXBMC and DSPlayer into the main branch but the DSPlayer is Windows specific and probably never get into the main branch so the solution would be to have SpotyXBMC in the main branch and have DSPlayer variant to be based on a new main branch version that includes SpotyXBMC.
Is that far off or can we expect Spoty to be merged into the main XBMC track soon?

**Comment by nilzen** [comment]
spotyxbmc binaries is only released against the latest stable xbmc version.

spotyxbmc will never be included in the xbmc trunk the way it's done today, but have a look at http://forum.xbmc.org/showthread.php?p=509176 and you'll see how it probably will be integrated with xbmc in the future.

**Comment by akezeke** [comment]
That is correct, but for now it "should" be pretty easy to apply the spotyxbmc patch on the DSPlayer branch and build it.
