### ISSUE TITLE
Unable to compile with the latest xbmc-svn

### ISSUE THREAD

**Issue by Kitof** [akezeke/spotyxbmc#15]
You used revision 27574, but the latest revision is 28256 it's a lot of commits ;)

**Comment by akezeke** [comment]
I have committed an update, here it now builds with revision 28310, but remember that the xbmc codebase is under constant change now so it might break again soon :)

**Comment by Kitof** [comment]
Thanks.

To fix the problem (and the complaint :) ) maybe you could specified a revision number in the readme, and update the svn command with the -r option ?

**Comment by Kitof** [comment]
There is an error in xbmc/Makefile.in. The file to add in the SRCS is spotinterface.cpp not spotifyinterface.cpp ;)

**Comment by akezeke** [comment]
damn, I fixed this once, but the latest commit was generated in windows where that error still existed :)
