### ISSUE TITLE
Crash when spotify account has no playlist

### ISSUE THREAD

**Issue by Kitof** [akezeke/spotyxbmc#2]

**Comment by akezeke** [comment]
Interesting, I will take a look at that later today

**Comment by noahwilliamsson** [comment]
I believe this crash was because of a bug in libopenspotify.
I've just commited a fix for it.

**Comment by akezeke** [comment]
Thanks Noah!

Can anyone confirm that this is not an issue anymore?

**Comment by akezeke** [comment]
in ubuntu that is, I have not made a new version for windows using the latest libopenspotify yet.

**Comment by akezeke** [comment]
This is not an issue in ubuntu anymore,

**Comment by nilzen** [comment]
If it's not an issue, shouldn't this issue be closed now? ;)

**Comment by akezeke** [comment]
Maby, but the issue might or might not still be on the windows version, its untested and I have not updated the installation package with a new libopenspotify yet :)

**Comment by akezeke** [comment]
With the alpha 013 the issue is gone in windows as well!
