### ISSUE TITLE
Cannot login, library too old

### ISSUE THREAD

**Issue by johey** [akezeke/spotyxbmc#28]
I just installed spotyxbmc, but after giving username and password, I get a message telling me the library is too old.

Can I update it in some way? Is it using libspotify or openspotify by default?

**Comment by edbo** [comment]
I just did a fresh install and I have the same problem

**Comment by johey** [comment]
I did not solve it either, since I got tired of it, but I believe you can update the library yourself in some way. And please come back with a success story when you have it. :)

**Comment by akezeke** [comment]
This is due to that spotify has made it impossibly to use the precompiled binaries, read my updated readme!
