### ISSUE TITLE
Error while loading shared libraries: libfaad.so.0

### ISSUE THREAD

**Issue by ghost** [akezeke/spotyxbmc#29]
Hi!
I get this message while trying to open xbmc after installing spotyxbmc for ubuntu32

Error while loading shared libraries: libfaad.so.0: cannot open shared object file: No such file or directory.

Help?

**Comment by akezeke** [comment]
This is an error with xbmc not the spotyxbmc implementation, ask at their forum.

**Comment by sommersohn** [comment]
Having the same problem after installing spotyxbmc. Before installing spotyxbmc it XBMC worked perfectly. After it, i get this error message. This IS a problem which spotyxbmc caused. By the way: I am using EDEN RC2.

ls -l  /usr/lib/libfaa*
-rw-r--r-- 1 root root  82614 2011-06-09 07:18 /usr/lib/libfaac.a
lrwxrwxrwx 1 root root     16 2011-06-09 07:18 /usr/lib/libfaac.so -> libfaac.so.0.0.0
lrwxrwxrwx 1 root root     16 2011-06-09 07:18 /usr/lib/libfaac.so.0 -> libfaac.so.0.0.0
-rw-r--r-- 1 root root  68608 2011-06-09 07:18 /usr/lib/libfaac.so.0.0.0
-rw-r--r-- 1 root root 293760 2010-11-23 17:11 /usr/lib/libfaad.a
lrwxrwxrwx 1 root root     16 2010-11-23 17:11 /usr/lib/libfaad.so -> libfaad.so.2.0.0
lrwxrwxrwx 1 root root     16 2010-11-23 17:11 /usr/lib/libfaad.so.2 -> libfaad.so.2.0.0
-rw-r--r-- 1 root root 251196 2010-11-23 17:11 /usr/lib/libfaad.so.2.0.0
