### ISSUE TITLE
No sound and flat visualisation

### ISSUE THREAD

**Issue by Kitof** [akezeke/spotyxbmc#3]
Extract of xbmc's log here : http://pastebin.com/m2b11d2b6

**Comment by akezeke** [comment]
Is this happening with all tracks?

**Comment by Kitof** [comment]
Yes, actually, the track never start.

I'm ready for further test if you want.

I use alsa 1.0.22.1 and i compile xbmc without pulseaudio.

Note that i use spdif output.

**Comment by akezeke** [comment]
Is the problem still there with the latest versions of spotyxbmc and openspotify?

**Comment by Kitof** [comment]
Exactly the same. I'm not able to start any of the song (Top Tracks, Top albums, Imported in library...)

**Comment by Kitof** [comment]
Ok with a fresh install IT WORKS !

Very good job akezeke.

I dreamed it, you did it ;)

**Comment by akezeke** [comment]
Good to hear!

**Comment by Tralla** [comment]
Kitof; fresh install of what?  I have the same issue, compiled xbmc, openspotify and spotyxbmc from source but still no sound :(

**Comment by Kitof** [comment]
Have-you disable pulseaudio during xbmc compilation ?

**Comment by Tralla** [comment]
Yes but now it works.. with no apparent change from my side.  Well sorta works, it seems if I restart xbmc a few times it starts working eventually so it seems there might be some lockup. Strange thing is that I can play non-spotify music every time.

But when it works its fabulous!
