### ISSUE TITLE
Green overlay when watching videos

### ISSUE THREAD

**Issue by atholm** [akezeke/spotyxbmc#6]
Hi
Thanks again for great plugin.
I do however have a problem not related to spotify plugin but in started to occur right after spotify install.
When I'm watching videos the image has a very green overlay. It looks like some codec problem, maybe after I installed transcode?

Please help

**Comment by atholm** [comment]
A complete uninstall of xbmc and reinstall fixed the problem BUT every time I install the spotify plugin the same problem gets back.
Am I missing some dependency or?

**Comment by atholm** [comment]
I have installed all dependencies as stated in the xbmc ubuntu readme

**Comment by nilzen** [comment]
This is a bug in the svn version of xbmc (http://trac.xbmc.org/ticket/8337), it has nothing to do with spotyxbmc. Not sure if you compiled it yourself or if you used the precompiled version, if it was the precompiled maybe this version should use the 9.11 tag instead of the trunk version of xbmc.

**Comment by atholm** [comment]
I use the precompiled version and have a Nvidia 7600Go card. So yea maybe the version should use the 9.11

**Comment by nilzen** [comment]
Ok then I put my vote for the 9.11 tag, if an user wants a precompiled binary then it should be a "working" one, if you like to play on the edge then you can compile the trunk and apply the patch yourself...

**Comment by atholm** [comment]
Aye!

**Comment by zaeta** [comment]
Did u get rid of the green overlay? Using 9.11 Camelot, ubuntu 9.10, and after installing spotyyxbmc it get's green. I'm I wrong about what version of xbmc to use?
No else getting this problem?

Forgot to say.. Awesome Plugin,

**Comment by atholm** [comment]
Still green for me!
But if you reinstall xbmc it will fix the problem, but you cannot use spotyxbmc and watch videos at the same time. 
Hope this will be fixed very soon

**Comment by akezeke** [comment]
Ok, I'm going to build a new binary with 9.11 stable!

**Comment by akezeke** [comment]
Now there is a version baes on XBMC 9.11 stable in the downloads, use it if you dont want green overlays :)

**Comment by zaeta** [comment]
That is just...So awesome =). Its really a great build

**Comment by atholm** [comment]
Thanks will test later today. Again many thanks!
