### ISSUE TITLE
Openspotify

### ISSUE THREAD

**Issue by ghost** [akezeke/spotyxbmc#7]
Thanks for this one, I have been wating for spotify on xbmc for ages! :D
This is probably really simple: after install, I get this error message..

/usr/share/xbmc/xbmc.bin: error while loading shared libraries: libopenspotify.so: cannot open shared object file: No such file or directory

Is there something I have missed or something I should remove?
Thanks!

**Comment by akezeke** [comment]
I guess there was an error during the libopenspotify installation phase. Visit  http://github.com/noahwilliamsson/openspotify and do the installation manually, its not hard.

**Comment by ghost** [comment]
I have tried to do the installation manually, but I seem to have a problem with "Vorbis"?
I took a closer look at my spotyxbmc installation and it reports the same thing:

xbmc@xbmc-desktop:~/Skrivbord/spotyxbmc_alpha012_ubuntu32$ sudo ./install.sh
Läser paketlistor... Färdig
Bygger beroendeträd  
Läser tillståndsinformation... Färdig
libssl-dev är redan den senaste versionen.
libvorbisfile3 är redan den senaste versionen.
zlib1g-dev är redan den senaste versionen.
git-core är redan den senaste versionen.
0 att uppgradera, 0 att nyinstallera, 0 att ta bort och 0 att inte uppgradera.
mkdir: kan inte skapa katalog "/home/xbmc/openspotify": Filen existerar
fatal: destination path 'openspotify' already exists and is not an empty directory.
rm -f aes.o browse.o buf.o cache.o channel.o commands.o dns.o ezxml.o handlers.o hashtable.o hmac.o link.o login.o iothread.o packet.o player.o playlist.o rbuf.o request.o search.o sha1.o shn.o toplistbrowse.o user.o util.o sp_album.o sp_artist.o sp_albumbrowse.o sp_artistbrowse.o sp_error.o sp_image.o sp_link.o sp_playlist.o sp_search.o sp_session.o sp_toplistbrowse.o sp_track.o sp_user.o libopenspotify.so
gcc -Wall -ggdb -I../include -fPIC -O2   -c -o aes.o aes.c
gcc -Wall -ggdb -I../include -fPIC -O2   -c -o browse.o browse.c
In file included from sp_opaque.h:30,
                 from commands.h:10,
                 from browse.c:37:
player.h:11:31: error: vorbis/vorbisfile.h: Filen eller katalogen finns inte
In file included from sp_opaque.h:30,
                 from commands.h:10,
                 from browse.c:37:
player.h:80: error: expected specifier-qualifier-list before ‘OggVorbis_File’
make: **\* [browse.o] Fel 1
gcc -Wall -ggdb -I../include -fPIC -O2 -DDEBUG   -c -o browse.o browse.c
In file included from sp_opaque.h:30,
                 from commands.h:10,
                 from browse.c:37:
player.h:11:31: error: vorbis/vorbisfile.h: Filen eller katalogen finns inte
In file included from sp_opaque.h:30,
                 from commands.h:10,
                 from browse.c:37:
player.h:80: error: expected specifier-qualifier-list before ‘OggVorbis_File’
make: **\* [browse.o] Fel 1
Looking for your xbmc.bin, this might take a while...
XBMC is installed
Copying binaries
Installation succesfull

Any ideas?

**Comment by akezeke** [comment]
Maby there are some dependencies missing in the script, I will check that later but I guess libvorbis-dev should do the trick

**Comment by akezeke** [comment]
added  libvorbis-dev to the script!

**Comment by ghost** [comment]
Great, ill check it out!
