### ISSUE TITLE
"ERROR: Spotifylog: track is not available in this region" after albums have been added to database and xbmc restarted

### ISSUE THREAD

**Issue by nicodemuz-zz** [akezeke/spotyxbmc#9]
All tracks/albums ever added to the database/library is unplayable after PC reboot.
In logfile it complains about region.
But I can do a Spotify search from within XBMC and play the tracks.

I live in Sweden and I don't access internet through a proxy.
I run XBMC on WinXP SP3 and a ION330 based PC.

Example of error in xbmc.log:
11:41:37 T:2576 M:2735730688  NOTICE: Spotifylog: init
11:41:37 T:2576 M:2735714304  NOTICE: Spotifylog: loading spotifyCodec, spotify:track:2ixQFHcF66r1liIxY9RaOP
11:41:37 T:2576 M:2735714304   ERROR: Spotifylog: track is not available in this region
11:41:37 T:2576 M:2735714304   ERROR: CAudioDecoder: Unable to Init Codec while loading file musicdb://2/20/-1/910.spotify
11:41:37 T:2576 M:2735722496   ERROR: Playlist Player: skipping unplayable item: 11, path [musicdb://2/20/-1/910.spotify]
11:41:37 T:2576 M:2735722496   ERROR: Spotifylog: createcodec: spotify
11:41:37 T:2576 M:2735714304  NOTICE: Spotifylog: init
11:41:37 T:2576 M:2735693824  NOTICE: Spotifylog: loading spotifyCodec, spotify:track:1B3bf6XLf7nxvS5Uo0OpRE
11:41:37 T:2576 M:2735693824   ERROR: Spotifylog: track is not available in this region
11:41:37 T:2576 M:2735693824   ERROR: CAudioDecoder: Unable to Init Codec while loading file musicdb://2/20/-1/911.spotify
11:41:37 T:2576 M:2735702016   ERROR: Playlist Player: skipping unplayable item: 12, path [musicdb://2/20/-1/911.spotify]
11:41:37 T:2576 M:2735702016   ERROR: Spotifylog: createcodec: spotify

When I successfully played searched music it looks like this:
11:42:27 T:2576 M:2727968768  NOTICE: Spotifylog: clean
11:42:28 T:2576 M:2727657472  NOTICE: Spotifylog: search results are done!
11:42:37 T:2576 M:2723905536  NOTICE: Spotifylog: clean
11:42:52 T:2576 M:2718973952  NOTICE: Spotifylog: clean
11:42:56 T:2576 M:2719600640   ERROR: Spotifylog: createcodec:
11:42:56 T:2576 M:2719567872  NOTICE: Spotifylog: init
11:42:56 T:2576 M:2719559680  NOTICE: Spotifylog: loading spotifyCodec, spotify:track:3zAIEkWOXsmnuE5Edl92MI
11:43:04 T:2576 M:2715447296  NOTICE: Spotifylog: clean

But then adding the Album gives the following in the log despite it looks ok from within XBMC:
11:43:04 T:2576 M:2715447296   ERROR: XFILE::CDirectory::GetDirectory - Error getting musicdb://spotify/command/addalbum/
11:43:04 T:2576 M:2715447296   ERROR: CGUIMediaWindow::GetDirectory(musicdb://spotify/command/addalbum/) failed
11:43:04 T:2576 M:2715443200  NOTICE: Spotifylog: clean
11:43:09 T:2576 M:2713354240  NOTICE: Spotifylog: clean
11:43:14 T:2576 M:2713124864  NOTICE: Spotifylog: clean
11:43:14 T:2576 M:2713124864   ERROR: XFILE::CDirectory::GetDirectory - Error getting musicdb://spotify/command/addalbum/
11:43:14 T:2576 M:2713124864   ERROR: CGUIMediaWindow::GetDirectory(musicdb://spotify/command/addalbum/) failed
11:43:14 T:2576 M:2713124864  NOTICE: Spotifylog: clean
11:43:21 T:2576 M:2710106112  NOTICE: Spotifylog: clean
11:43:25 T:2576 M:2711818240  NOTICE: Spotifylog: clean

ANy ideas of what goes wrong?

**Comment by akezeke** [comment]
My bad, issue solved in alpha 014!
